/* eslint-disable @next/next/no-img-element */
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { ReactNode } from 'react';
import { selectUser } from '../features/user/userSlice';
import { useLoginCheck } from '../hooks/useLoginCheck';
import { useAppSelector } from '../hooks/useRTK';
import { UserType } from '../types/UserType';

const Layout = ({
  children,
  title = 'HP by yus',
}: {
  children: ReactNode;
  title?: string;
}) => {
  const isLogin = useLoginCheck();
  const user: UserType = useAppSelector(selectUser);
  const { data } = useSession();

  return (
    <div className="flex justify-center items-center flex-col min-h-screen text-gray-600 text-sm font-mono">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="bg-gray-800 w-screen">
          <div className="flex items-center pl-8 h-14">
            <div className="flex space-x-4">
              <Link href="/">
                <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                  Home
                </a>
              </Link>
              <Link href="/blog-page">
                <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                  Blog
                </a>
              </Link>
              <Link href="/ec-page">
                <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                  EC
                </a>
              </Link>
              <Link href="/crud-page">
                <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                  CRUD
                </a>
              </Link>
              <Link href="/contact-page">
                <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                  Contact
                </a>
              </Link>
            </div>
            <div className="ml-auto pr-4">
              {data?.user ? (
                <img
                  className="rounded-full cursor-pointer"
                  src={`${user.photoUrl}`}
                  width={40}
                  height={40}
                  onClick={() => signOut()}
                  alt="Avatar"
                />
              ) : (
                <a
                  className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded cursor-pointer"
                  onClick={() => signIn()}
                >
                  Login
                </a>
              )}
            </div>
          </div>
        </nav>
      </header>
      <main className="flex flex-1 justify-center items-center flex-col w-screen">
        {children}
      </main>
      <footer className="w-full h-12 flex justify-center items-center border-t">
        <a
          className="flex items-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </div>
  );
};

export default Layout;
